// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEMl3mdwUIkesOzpxslL7C4cZZucmbQvc',
    appId: '1:474708093013:web:0fd24c1feb647d454a8cdc',
    messagingSenderId: '474708093013',
    projectId: 'login-df074',
    authDomain: 'login-df074.firebaseapp.com',
    storageBucket: 'login-df074.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLKJII7ZiY7e-EWxQpJWDdW4GnIBHSKf4',
    appId: '1:474708093013:android:bb947ae7a29f23e04a8cdc',
    messagingSenderId: '474708093013',
    projectId: 'login-df074',
    storageBucket: 'login-df074.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWaJSPNfQJJgLcPb2g7K6364j5UPJeizY',
    appId: '1:474708093013:ios:b079d85e1500b8344a8cdc',
    messagingSenderId: '474708093013',
    projectId: 'login-df074',
    storageBucket: 'login-df074.appspot.com',
    iosClientId: '474708093013-r0f6tgsthqnt6gtfj7h2lk5n12et5ntk.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWaJSPNfQJJgLcPb2g7K6364j5UPJeizY',
    appId: '1:474708093013:ios:b079d85e1500b8344a8cdc',
    messagingSenderId: '474708093013',
    projectId: 'login-df074',
    storageBucket: 'login-df074.appspot.com',
    iosClientId: '474708093013-r0f6tgsthqnt6gtfj7h2lk5n12et5ntk.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPage',
  );
}
